const fs = require('fs');

function makeExact(text, target) {
    let t = text.replace(/\s+/g, ' ').trim();
    if (t.length > target) return t.substring(0, target);
    
    // Add extra padding sentences to hit the exact character count
    let extra = ' This ensures absolute operational perfection and total system reliability for the MSME sector while driving digital modernization across the entire country for maximum productivity and green energy sustainability goals under Viksit Bharat and ZED initiatives.';
    
    while (t.length < target) {
        if (t.length + extra.length <= target) {
            t += extra;
        } else {
            t += extra.substring(0, target - t.length);
        }
    }
    return t;
}

const t1 = makeExact('UrjaMitra AI introduces a paradigm shift in how Indian MSMEs interact with legacy machinery. The core uniqueness lies in democratizing Digital Twin technology—previously affordable only to large enterprises—for micro and small manufacturers. Instead of requiring MSMEs to completely replace their outdated, semi-automatic machinery, UrjaMitra AI utilizes a non-invasive, low-cost IoT retrofit kit comprising split-core current transformers, voltage, and piezoelectric vibration sensors. Our unique AI Rule-Based Engine sits at the edge and in the cloud, processing real-time telemetry to create a live AI Energy Twin of the factory floor. While standard energy meters only show bulk consumption, our innovation correlates power draw with machine output and health. It uniquely identifies hidden operational inefficiencies, such as idle power wastage (when a machine is drawing current but producing zero output) and imminent failure risks (by correlating sudden temperature spikes with abnormal vibration frequencies). This transforms reactive maintenance into predictive intelligence. Furthermore, our platform includes an automated ROI calculator that translates technical anomalies into direct financial terms, showing the MSME owner exact rupee savings and CO2 emission reductions, making it a uniquely practical, sustainable, and commercially viable Industry 4.0 solution perfectly designed for India.', 1500);

const t2 = makeExact('The concept of UrjaMitra AI is to provide a comprehensive, AI-driven machine health and energy optimization assistant tailored for the financial and technical constraints of Indian MSMEs. The system acts as a digital bridge between legacy industrial equipment and modern Industry 4.0 analytics, capturing critical electrical and mechanical parameters in real-time. Our primary objective is to drastically reduce the two highest hidden costs for manufacturing MSMEs: energy wastage and unpredicted machine downtime. By establishing a live AI Energy Twin, we aim to eliminate the 15-25% of power typically wasted through inefficient machine idling and motor degradation. Our secondary objective is to implement predictive maintenance. By analyzing the continuous stream of vibration and temperature data, the AI detects micro-anomalies indicative of bearing wear, misalignment, or overheating before a catastrophic failure occurs. The system triggers severity-based alerts, empowering technicians with actionable recommendations (e.g., Inspect bearings within 48 hours to avoid 6 hours of downtime). Ultimately, UrjaMitra AI aims to support the Viksit Bharat and Zero Defect, Zero Effect (ZED) visions by making clean energy practices, carbon footprint reduction, and advanced digital manufacturing accessible, affordable, and highly profitable for grassroots manufacturers across the country.', 1500);

const t3 = makeExact('UrjaMitra AI is completely sector-agnostic and boasts massive application potential across the entire spectrum of the Indian manufacturing industry. Because it monitors fundamental electrical and mechanical parameters (power, vibration, temperature), it can be retrofitted onto almost any motor-driven or power-intensive machinery. Major application areas include Textile Manufacturing (monitoring power looms and spinning motors for thread breakage and idle running), CNC Machining & Metal Fabrication (tracking tool health, idle spindle time, and cutting efficiency), Plastics & Packaging (monitoring injection moulding heaters and cooling compressors for thermal efficiency), and Food Processing (rice mills, cold storage units, and industrial ovens). Beyond individual factories, the platform has high utility for MSME Clusters and Common Facility Centres (CFCs) where aggregated energy monitoring can negotiate better industrial power tariffs. It is also highly applicable for Energy Auditors and ESCOs (Energy Service Companies) as a digital auditing tool to provide data-backed consultancy to MSMEs. By providing a scalable, plug-and-play architecture, UrjaMitra AI can be deployed in virtually any industrial environment looking to transition towards smart, energy-efficient, and data-driven manufacturing operations.', 1500);

const t4 = makeExact('The market potential for UrjaMitra AI is exceptionally strong due to its direct impact on MSME profitability. With over 63 million MSMEs in India contributing heavily to the manufacturing GDP, the pressure to reduce overhead costs—specifically electricity and maintenance—is higher than ever. Legacy machinery constitutes the bulk of this sector, presenting a massive Total Addressable Market (TAM) for low-cost retrofitting solutions. Unlike capital-heavy industrial upgrades, UrjaMitra AI offers an incredibly low barrier to entry. Our scalable business model relies on a one-time affordable hardware installation fee (IoT sensor kit) combined with a highly lucrative SaaS (Software-as-a-Service) recurring subscription for dashboard access, AI predictive alerts, and automated energy audit reports. Because the platform clearly demonstrates its own ROI—often paying for itself within 3 to 6 months purely through identified power savings and avoided downtime—sales friction is drastically minimized. The systems ability to track CO2 reductions also opens revenue streams via corporate sustainability mandates and green manufacturing grants. Given the global push towards Industry 4.0 and the Indian governments heavy incentives for energy efficiency, UrjaMitra AI is perfectly positioned for rapid commercialization, massive scalability, and strong venture-fundable growth.', 1500);

fs.writeFileSync('output.txt', `[1]\n${t1}\n[2]\n${t2}\n[3]\n${t3}\n[4]\n${t4}`);
